# Problem 1 

In [4]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.random.randint(0, 100, 5)
print("Orijinal array:", array)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın
sorted_array = np.sort(array)
print("Sıralanmış array:", sorted_array)


Orijinal array: [90 86 63 33 92]
Sıralanmış array: [33 63 86 90 92]


# Problem 2

In [7]:
import numpy as np

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array1 = np.array([10, 15, 30, 45, 60])
print("Array 1: ", array1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array2 = np.arange(5, 16)
print("Array 2: ", array2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array3 = np.arange(50, 101, 5)
print("Array 3: ", array3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array4 = np.zeros(10)
print("Array 4: ", array4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array5 = np.ones(10)
print("Array 5: ", array5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array6 = np.linspace(0, 100, 5)
print("Array 6: ", array6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
array7 = np.random.randint(10, 31, 5)
print("Array 7: ", array7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array8 = np.linspace(-1, 1, 10)
print("Array 8: ", array8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matrix = np.random.randint(10, 51, size=(3, 5))
print("Matrix:\n ", matrix)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız.
satir_toplamlari = np.sum(matrix, axis=1)
sutun_toplamlari = np.sum(matrix, axis=0)
print("Satır toplamları: ", satir_toplamlari)
print("Sütun toplamları: ", sutun_toplamlari)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir?
en_buyuk = np.max(matrix)
en_kucuk = np.min(matrix)
ortalama = np.mean(matrix)
print("En büyük değer: ", en_buyuk)
print("En küçük değer: ", en_kucuk)
print("Ortalama: ", ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır?
en_buyuk_indeks = np.unravel_index(np.argmax(matrix), matrix.shape)
print("En büyük değerin indeksi: ", en_buyuk_indeks)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array13 = np.arange(10, 21)
print("Array 13: ", array13[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print("Array 13 ters: ", array13[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print("Matrisin ilk satırı: ", matrix[0])

# 16- Üretilen matrisin 2. satır 3. sütundaki elemanı hangisidir?
print("Matrisin 2. satır 3. sütundaki elemanı: ", matrix[1, 2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("Matrisin tüm satırlardaki ilk elemanı: ", matrix[:, 0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
matrix_karesi = np.square(matrix)
print("Matrisin kareleri:\n ", matrix_karesi)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır? Aralığı (-50,+50) arasında yapınız.
matrix_genis = np.random.randint(-50, 51, size=(3, 5))
print("Geniş aralık matris:\n ", matrix_genis)
pozitif_ciftler = matrix_genis[(matrix_genis > 0) & (matrix_genis % 2 == 0)]
print("Pozitif çift sayılar: ", pozitif_ciftler)


Array 1:  [10 15 30 45 60]
Array 2:  [ 5  6  7  8  9 10 11 12 13 14 15]
Array 3:  [ 50  55  60  65  70  75  80  85  90  95 100]
Array 4:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array 5:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array 6:  [  0.  25.  50.  75. 100.]
Array 7:  [21 28 10 13 12]
Array 8:  [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
Matrix:
  [[13 34 30 22 40]
 [22 44 33 46 42]
 [14 13 44 46 26]]
Satır toplamları:  [139 187 143]
Sütun toplamları:  [ 49  91 107 114 108]
En büyük değer:  46
En küçük değer:  13
Ortalama:  31.266666666666666
En büyük değerin indeksi:  (np.int64(1), np.int64(3))
Array 13:  [10 11 12]
Array 13 ters:  [20 19 18 17 16 15 14 13 12 11 10]
Matrisin ilk satırı:  [13 34 30 22 40]
Matrisin 2. satır 3. sütundaki elemanı:  33
Matrisin tüm satırlardaki ilk elemanı:  [13 22 14]
Matrisin kareleri:
  [[ 169 1156  900  484 1600]
 [ 484 1936 1089 2116 1764]
 [ 196  169 1936 2116  676]]
Geniş aralık ma